services:
  - type: web
    name: whatsapp-chat-analyzer
    env: python
    region: oregon # Choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py 
    plan: free
